# PROBLEM 1: Recommender System using Collaborative Filtering

In [25]:
import pandas as pd

df = pd.read_csv("ml-100k/u.data", sep='\t', names=["userId", "movieId", "rating", "timestamp"])
df.drop(columns=["timestamp"], inplace=True)

In [26]:
df

       userId  movieId  rating
0         196      242       3
1         186      302       3
2          22      377       1
3         244       51       2
4         166      346       1
...       ...      ...     ...
99995     880      476       3
99996     716      204       5
99997     276     1090       1
99998      13      225       2
99999      12      203       3

[100000 rows x 3 columns]

In [27]:
df.describe()

             userId        movieId         rating
count  100000.00000  100000.000000  100000.000000
mean      462.48475     425.530130       3.529860
std       266.61442     330.798356       1.125674
min         1.00000       1.000000       1.000000
25%       254.00000     175.000000       3.000000
50%       447.00000     322.000000       4.000000
75%       682.00000     631.000000       4.000000
max       943.00000    1682.000000       5.000000

In [28]:
df.isnull().sum()

userId     0
movieId    0
rating     0
dtype: int64

In [32]:
df.dtypes

userId     int64
movieId    int64
rating     int64
dtype: object

In [62]:
df['movieId'].nunique()

1682

In [113]:
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)

In [114]:
user_df = train_df.merge(train_df, on='movieId')
user_df = user_df[user_df['userId_x'] != user_df['userId_y']]

In [115]:
user_df['ratings_product'] = user_df['rating_x'] * user_df['rating_y']

In [116]:
grouped = user_df.groupby(['userId_x', 'userId_y'])['ratings_product'].mean().reset_index()

In [117]:
grouped

        userId_x  userId_y  ratings_product
0              1         2        18.636364
1              1         3         7.000000
2              1         4         7.500000
3              1         5        12.934783
4              1         6        15.637931
...          ...       ...              ...
831959       943       938        11.529412
831960       943       939        17.750000
831961       943       940        15.550000
831962       943       941        17.400000
831963       943       942        16.083333

[831964 rows x 3 columns]

In [118]:
import numpy as np

In [119]:
similarity_dict = {
    (row['userId_x'], row['userId_y']): row['ratings_product']
    for _, row in grouped.iterrows()
}

rating_mat = np.zeros((943, 943))

for i in tqdm(range(1, 944), desc="Filling matrix from dict"):
    for j in range(1, 944):
        if i == j:
            continue
        
        value = similarity_dict.get((i, j), 0)
        rating_mat[i-1, j-1] = value

Filling matrix from dict: 100%|██████████| 943/943 [00:00<00:00, 1906.10it/s]

In [121]:
test_df

       userId  movieId  rating
75721     877      381       4
80184     815      602       3
19864      94      431       4
76699     416      875       2
92991     500      182       2
...       ...      ...     ...
32595      72      591       5
29313     523      393       5
37862     606      287       4
53421     650      612       4
42410     303       72       3

[20000 rows x 3 columns]

In [127]:
from tqdm import tqdm

pred = []

for i in tqdm(range(test_df.shape[0]), desc="Predicting ratings"):
    curr_user_id = test_df.iloc[i, 0]
    curr_movie_id = test_df.iloc[i, 1]

    movie_watched = train_df[train_df['movieId'] == curr_movie_id]

    curr_sum = 0
    curr_prod_sum = 0

    for j in range(movie_watched.shape[0]): 
        curr_rating = movie_watched.iloc[j, 2]
        B = movie_watched.iloc[j, 0]
        sim_AB = rating_mat[curr_user_id-1][B-1]
        curr_prod_sum += (sim_AB * curr_rating)
        curr_sum += sim_AB

    if curr_prod_sum == 0 or curr_sum == 0:
        pred.append(0)
    else:
        pred.append(curr_prod_sum / curr_sum)

Predicting ratings: 100%|██████████| 20000/20000 [01:27<00:00, 228.68it/s]

In [131]:
actual = test_df['rating'].to_list()

In [133]:
from sklearn.metrics import mean_squared_error
import numpy as np

rmse = np.sqrt(mean_squared_error(actual, pred))
print("RMSE:", rmse)

RMSE: 1.0239264065486657